print('program 8')
x=int(input('podaj liczbe x'))
y=int(input('podaj liczbe y'))
print(x, "+" ,y, "=", x+y)
print(x, "-" ,y, "=", x-y)
print(x, "*" ,y, "=", x*y)
print(x, "/" ,y, "=", x/y)
print(x, "//",y, "=", x//y)
print(x, "%" ,y, "=", x%y)
print(x, "**" ,y, "=", x**y)

print('program oblicza sume n kolejnych liczb naturalnych')
n=int(input('podaj n'))
k=n*(n+1)/2
print('suma kolejnych',n,'liczb naturalnych wynosi', k)